### ISSUE TITLE
Trying to inference using the lora adapter (from fine-tuning) and the base model and not working

### ISSUE THREAD

**Issue by JSeuma** [haotian-liu/LLaVA#1008]
### Describe the issue

Issue:
I have fine-tune the liuhaotian/llava-v1.5-7b model and I have the output in ./checkpoints/llava-v1.5-7b-task-lora. I try to do the inference with only the base model and it works, but when I try to do inference including the lora adapter it gives me error:

Code for inference with lora adpter:
python -m llava.serve.cli     --model-path ./checkpoints/llava-v1.5-7b-task-lora    --model-base liuhaotian/llava-v1.5-7b     --image-file ./playground/data/textvqa/train_images/00a108e5e2160b20.jpg     --load-4bit

I put the adapter as the model-path and the base model as model-base. The error code is below, any idea what I am doing wrong?. Thanks in advance.

[2024-01-23 12:05:56,258] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Loading LLaVA from base model...
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:07<00:00,  3.54s/it]
Loading additional LLaVA weights...
Traceback (most recent call last):
  File "/home/jseuma/miniconda3/envs/llava/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/jseuma/miniconda3/envs/llava/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/jseuma/LLaVA/llava/serve/cli.py", line 124, in <module>
    main(args)
  File "/home/jseuma/LLaVA/llava/serve/cli.py", line 32, in main
    tokenizer, model, image_processor, context_len = load_pretrained_model(args.model_path, args.model_base, model_name, args.load_8bit, args.load_4bit, device=args.device)
  File "/home/jseuma/LLaVA/llava/model/builder.py", line 75, in load_pretrained_model
    model.load_state_dict(non_lora_trainables, strict=False)
  File "/home/jseuma/miniconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for LlavaLlamaForCausalLM:
        size mismatch for model.mm_projector.0.weight: copying a param with shape torch.Size([4096, 1024]) from checkpoint, the shape in current model is torch.Size([2097152, 1]).
        size mismatch for model.mm_projector.2.weight: copying a param with shape torch.Size([4096, 4096]) from checkpoint, the shape in current model is torch.Size([8388608, 1]).

**Comment by AnjanGiri** [comment]
I am also getting the same error when trying to load the Finetuned Lora checkpoint using the following code:
`from llava.model.builder import load_pretrained_model

tokenizer, model, image_processor, context_len = load_pretrained_model(
            "/data/image_captioning_data/checkpoints_2/llava-v1.5-7b-task-lora/checkpoint-5",
            model_name="liuhaotian/llava-v1.5-7b-lora-finetuned",
            model_base="liuhaotian/llava-v1.5-7b",
            load_8bit=False, 
            load_4bit=True)`
I am getting the following error:
`RuntimeError                              Traceback (most recent call last)
Cell In[1], line 3
      1 from llava.model.builder import load_pretrained_model
----> 3 tokenizer, model, image_processor, context_len = load_pretrained_model(
      4             "/data/image_captioning_data/checkpoints_2/llava-v1.5-7b-task-lora/checkpoint-5",
      5             model_name="liuhaotian/llava-v1.5-7b-lora-finetuned",
      6             model_base="liuhaotian/llava-v1.5-7b",
      7             load_8bit=False, 
      8             load_4bit=True)

File ~/Anjan/exp_image_captioning/LLaVA/llava/model/builder.py:79, in load_pretrained_model(model_path, model_base, model_name, load_8bit, load_4bit, device_map, device, use_flash_attn, **kwargs)
     77 if any(k.startswith('model.model.') for k in non_lora_trainables):
     78     non_lora_trainables = {(k[6:] if k.startswith('model.') else k): v for k, v in non_lora_trainables.items()}
---> 79 model.load_state_dict(non_lora_trainables, strict=False)
     81 from peft import PeftModel
     82 print('Loading LoRA weights...')

File ~/miniconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py:2153, in Module.load_state_dict(self, state_dict, strict, assign)
   2148         error_msgs.insert(
   2149             0, 'Missing key(s) in state_dict: {}. '.format(
   2150                 ', '.join(f'"{k}"' for k in missing_keys)))
   2152 if len(error_msgs) > 0:
-> 2153     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
   2154                        self.__class__.__name__, "\n\t".join(error_msgs)))
   2155 return _IncompatibleKeys(missing_keys, unexpected_keys)

RuntimeError: Error(s) in loading state_dict for LlavaLlamaForCausalLM:
	size mismatch for model.mm_projector.0.weight: copying a param with shape torch.Size([4096, 1024]) from checkpoint, the shape in current model is torch.Size([2097152, 1]).
	size mismatch for model.mm_projector.2.weight: copying a param with shape torch.Size([4096, 4096]) from checkpoint, the shape in current model is torch.Size([8388608, 1]).`

**Comment by 1716757342** [comment]
I also encountered the same problem, have you solved it? thank you.

**Comment by 1716757342** [comment]
You need to first meger base model and lora model with the following code.

python scripts/merge_lora_weights.py \
--model-path /path/to/llava-v1.5-13b-lora \
--model-base LLaVA_train \
--save-model-path merge_model

Then use the post-meger run and you're done.

**Comment by zhyhome** [comment]
> You need to first meger base model and lora model with the following code.
> 
> python scripts/merge_lora_weights.py --model-path /path/to/llava-v1.5-13b-lora --model-base LLaVA_train --save-model-path merge_model
> 
> Then use the post-meger run and you're done.

I merged,but this model can't gengrate anything.

**Comment by Yrdal3910** [comment]
I encountered the same issue. For me, the error occurred when I added the parameter "--load-4bit" while launching the model worker. It appears that the base model uses 8-bit storage because inference runs smoothly either when I remove this parameter or switch to "--load-8bit". This also explains why 4096 * 1024 equals 4194304, which is double 2097152.

**Comment by psvkaushik** [comment]
> I encountered the same issue. For me, the error occurred when I added the parameter "--load-4bit" while launching the model worker. It appears that the base model uses 8-bit storage because inference runs smoothly either when I remove this parameter or switch to "--load-8bit". This also explains why 4096 * 1024 equals 4194304, which is double 2097152.

I'm trying to run the MMbench using the merged model but still getting empty strings as output, can you maybe coomen on that? I actually raised it as an issue for more context : [issue](https://github.com/haotian-liu/LLaVA/issues/1752)
