### ISSUE TITLE
[Usage] Some Weights not used, when loaded llava-v1.5-7b to test

### ISSUE THREAD

**Issue by Gear420** [haotian-liu/LLaVA#673]
### Describe the issue

Issue:

Command:
```
python cli.py --model-path liuhaotian/llava-v1.5-7b  --load-4bit --image-file "https://llava-vl.github.io/static/images/view.jpg" --debug

```

Log: 
```
 [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Loading checkpoint shards: 100%|██████████████████████████████████████| 2/2 [00:13<00:00,  6.54s/it]
Some weights of the model checkpoint at /home/users/xingyu.zhang/.cache/huggingface/hub/models--liuhaotian--llava-v1.5-7b/snapshots/12e054b30e8e061f423c7264bc97d4248232e965/ were not used when initializing LlavaLlamaForCausalLM: ['model.mm_projector.0.bias', 'model.mm_projector.0.weight', 'model.mm_projector.2.weight', 'model.mm_projector.2.bias']
- This IS expected if you are initializing LlavaLlamaForCausalLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing LlavaLlamaForCausalLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of LlavaLlamaForCausalLM were not initialized from the model checkpoint at /home/users/xingyu.zhang/.cache/huggingface/hub/models--liuhaotian--llava-v1.5-7b/snapshots/12e054b30e8e061f423c7264bc97d4248232e965/ and are newly initialized: ['model.mm_projector.bias', 'model.mm_projector.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
```

Screenshots:
After reinitializing the mm_projector, it produces incorrect answers：
![img_v2_ac90056f-cf76-4cc1-b8b3-5c19f13e11dg](https://github.com/haotian-liu/LLaVA/assets/26384036/6e51669b-341c-4850-8597-65fe6ec1cc7d)

**Comment by haotian-liu** [comment]
Hi, can you verify if you are using the latest code base? Older code base does not support the MLP projector in LLaVA-v1.5

**Comment by Gear420** [comment]
Thank you for your reply! I have updated the code to the latest version and resolved this issue.

**Comment by qzp2018** [comment]
I also meet the same question when using my own pretrained projector for inference. I update the code but the issue still exists. Does the transformer version also matter?

**Comment by bryanwong17** [comment]
Hi, how can I resolve this issue? Is this warning critical or can it be safely ignored?

**Comment by ShristiDasBiswas** [comment]
Hi, were you able to solve this issue? Would greatly appreciate some pointers! Thanks!
